import { config } from 'dotenv';
config();
const ws = require('ws');
const { neonConfig, Pool } = require('@neondatabase/serverless');
const { PrismaNeon } = require('@prisma/adapter-neon');
const { PrismaClient } = require('@prisma/client');
neonConfig.webSocketConstructor = ws;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaNeon(pool);
const prisma = new PrismaClient({ adapter });
prisma.$queryRaw`SELECT version()`.then(r => { console.log('OK:', r[0].version); process.exit(0); }).catch(e => { console.error('FAIL:', e.message); process.exit(1); });
